/*
 * appcb_Button.h
 *
 *  Created on: Dec 21, 2023
 *      Author: Rahma
 */

#ifndef DFU_USB_BOOTLOADER_APP_CALLBACK_APPCB_BUTTON_INC_APPCB_BUTTON_H_
#define DFU_USB_BOOTLOADER_APP_CALLBACK_APPCB_BUTTON_INC_APPCB_BUTTON_H_

void APPCB_Button(void);

#endif /* DFU_USB_BOOTLOADER_APP_CALLBACK_APPCB_BUTTON_INC_APPCB_BUTTON_H_ */
